var a = new Error("Error");
try {
    throw a;
} catch (e) {
    
} finally {

}